version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: t3-skeleton-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: t3_skeleton
    ports:
      - "5434:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # backend:
  #   build: ./backend
  #   container_name: t3-skeleton-backend
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - ./backend:/app
  #     - /app/node_modules
  #   environment:
  #     NODE_ENV: development
  #     PORT: 5000
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/t3_skeleton
  #   depends_on:
  #     - postgres

  # frontend:
  #   build: ./frontend
  #   container_name: t3-skeleton-frontend
  #   ports:
  #     - "8080:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules
  #   environment:
  #     VITE_API_URL: http://localhost:5000
  #   depends_on:
  #     - backend

volumes:
  pgdata:
